### ISSUE TITLE
nodejs : Conflicts: npm

### ISSUE THREAD

**Issue by ikbear** [axa-group/radar#244] opened 2020-02-29 06:38 UTC
**Describe the bug**

I encounter this problem when running "docker-compose up -d" command first time:

```
The following packages have unmet dependencies:
 nodejs : Conflicts: npm
 npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'radar' failed to build: The command '/bin/sh -c apt-get install -y build-essential nodejs npm' returned a non-zero code: 100
```
**To Reproduce**

Run:
```
docker-compose up -d
```

**Screenshots**

<img width="1001" alt="Screen Shot 2020-02-29 at 14 36 59" src="https://user-images.githubusercontent.com/232018/75602511-198d3180-5b01-11ea-8e8d-6fde4d2d6f68.png">

**Desktop (please complete the following information):**
 - macOS 10.5.3

**Comment by guillaume-chervet** [comment] 2020-03-06 19:44
Hi @ikbear 

Thank you for the issue. Sorry for the delay.
We do not have the problem on the latest version on master.
We use doker for Windows. We have to fond a mac un ordre to test.

**Comment by guillaumechervetaxa** [comment] 2020-03-16 08:25
@bernard-arnaud, I have this error on master now

![image](https://user-images.githubusercontent.com/43414465/76736936-16807b00-6768-11ea-93a6-2d0dd35df0f9.png)

**Comment by guillaume-chervet** [comment] 2020-05-17 20:45
It is working. Very sorry for the delay!

**Comment by ikbear** [comment] 2020-05-18 03:16
> It is working. Very sorry for the delay!

Thanks. It works. But there is a new error:

> The following packages have unmet dependencies:
 nodejs : Conflicts: npm
 npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'radar' failed to build: The command '/bin/sh -c apt-get install -y build-essential nodejs npm' returned a non-zero code: 100

**Comment by guillaumechervetaxa** [comment] 2020-05-20 06:53
I @ikbear,

I tried on 2 computer and I cannot reproduce the problem. 
Do you use the lastest version on master?

**Comment by ikbear** [comment] 2020-05-20 09:43
npm can be removed from `apt-get` when installing nodejs. It can be installed with nodejs. I have corrected it with a modified Dockerfile.

**Comment by ikbear** [comment] 2020-05-20 09:45
File: `/src/RadarTechno/Dockerfile`:

> -RUN apt-get install -y build-essential nodejs npm
> +RUN apt-get install -y build-essential nodejs

**Comment by bernard-arnaud** [comment] 2020-08-27 08:49
From [npmjs documentation](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) :
The Node installation process installs npm in a directory with local permissions and can cause permissions errors when you run npm packages globally.

I still think we should install nodejs and npm separately.
Closing this issue since we can't reproduce, let us know if the problem persists.

**Closed by bernard-arnaud** 2020-08-27 08:49 UTC
